### ISSUE TITLE
South gera erros ao utilizar BRDecimalField

### ISSUE THREAD

**Issue by jklemm** [znc-sistemas/django-localbr#2]
Sei que não é um erro direto com este projeto, porém creio que a chance é grande de quem estiver utilizando Django, utilizar também o South Migrations, e com isso, os campos deste projeto causam erros no South:

```bash
python manage.py schemamigration vendas --initial
Creating migrations directory at '/vendas/migrations'...
Creating __init__.py in '/vendas/migrations'...
 ! Cannot freeze field 'vendas.cupomdesconto.porcentagem'
 ! (this field has class utils.modelfields.BRDecimalField)

 ! South cannot introspect some fields; this is probably because they are custom
 ! fields. If they worked in 0.6 or below, this is because we have removed the
 ! models parser (it often broke things).
 ! To fix this, read http://south.aeracode.org/wiki/MyFieldsDontWork
```

Já li o endereço que o South recomenda, mas não consegui entender como posso utilizar um field  `BRDecimalField` usando o método `add_introspection_rules`.

Acredito que isso vale pelo menos uma dica no readme do projeto, ou senão um pedaço de código comentado nas fields, informando como fazer se tiver usando o djando-localbr com o South.

Grato.

**Comment by zokis** [comment]
o BRDecimalField é um form field e não um Model Field, ele deve ser utilizado nos forms
acho que você colocou ele em um model e é por isso que está dando erro

um exemplo básico de utilização seria

models.py
```python
class MeuModelo(models.Model):
    nome = models.CharField(u'Nome', max_length=100)
    campo_decimal = models.DecimalField(max_digits=12, decimal_places=4)
    
    def __unicode__(self):
        return self.nome
```


forms.py
```python
class MeuModeloForm(forms.ModelForm):
    campo_decimal = BRDecimalField(label=u"Label", required=True)

    class Meta:
        model = MeuModelo
```

**Comment by jklemm** [comment]
Grato pelo retorno!
